- docker-compose.yml
https://github.com/home-assistant/core/releases/tag/2021.4.3
> Update to homeassistant-core v2021.4

- README.md
- app/Dockerfile
- app/hostname.sh
- docker-compose.yml
> Set hostname on startup

- .github/workflows/versionist.yml
- docker-compose.yml
- mqtt/Dockerfile
- mqtt/mosquitto.conf
> restore mqtt persistence

- .github/workflows/balena.yml
- balena.yml
- docker-compose.yml
https://github.com/home-assistant/core/releases/tag/2021.11.5
> Update homeassistant to 2021.11.5

- balena.yml
- docker-compose.yml
https://github.com/home-assistant/core/releases/tag/2021.12.1
> Update homeassistant to 2021.12

- balena.yml
- docker-compose.yml
https://www.home-assistant.io/blog/2022/04/06/release-20224/
> Update homeassistant to 2022.4.1

- renovate.json
> Enable renovate for PRs for testing

- docker-compose.yml
- volume-keeper/Dockerfile.template
> Deploy experimental volume-keeper service for backups

- docker-compose.yml
- restic/Dockerfile.template
- volume-keeper/Dockerfile.template
> FIx path to balena-restic

- docker-compose.yml
> Update balena-restic to v2.0.0

- README.md
- docker-compose.yml
- frigate/Dockerfile.template
- zigbee2mqtt/Dockerfile
- zigbee2mqtt/configuration.yaml
> Install frigate and wyze-bridge services

- docker-compose.yml
> Use named volume for restic snapshots and tmpfs for mqtt logs

- frigate/Dockerfile.template
https://github.com/blakeblackshear/frigate/releases/tag/v0.11.0
> frigate: Update frigate to 0.11.0

- docker-compose.yml
Resolves: https://github.com/klutchell/balena-homeassistant/issues/210
> Enable access to bluetooth on the host via dbus

- .github/renovate.json
- docker-compose.yml
- restic/Dockerfile.template
- tailscale/Dockerfile.template
> Update tailscale service settings

- .github/renovate.json
> Remove regex managers that were added to klutchell/renovate-config

- docker-compose.yml
> Run as privileged to access all devices

- docker-compose.yml
- tailscale/Dockerfile.template
> Update tailscale block slug

- README.md
- docker-compose.yml
> Add netdata service

- README.md
- docker-compose.yml
- restic/Dockerfile.template
> Switch from restic to duplicati

- docker-compose.yml
> Create tmpfs for duplicati

- docker-compose.yml
> Share quicksync device with frigate service

- docker-compose.yml
- zigbee2mqtt/configuration.yaml
Also set the restart policy to "no" so the service remains stopped if the device is not found.
> Change the default device for zigbee2mqtt to ttyACM0

- docker-compose.yml
See: https://github.com/klutchell/balena-homeassistant/issues/773
> Update duplicati tag to 2.0.8
